/**
 * Whop API client for server-side calls.
 *
 * Every call here uses a server-only credential and must therefore run inside
 * a Convex action or HTTP action, never in the app.
 */

import { WHOP_API_BASE, WHOP_OAUTH_BASE, type WhopMembership } from "./_whop";

/** Tokens returned by the Whop OAuth token endpoint. */
interface WhopTokenResponse {
  access_token: string;
}

/** Identity returned by the Whop OIDC userinfo endpoint. */
interface WhopUserInfo {
  sub: string;
}

/** Reads the credential used to exchange OAuth authorization codes. */
function requireOAuthClientSecret(): string {
  const secret = process.env.WHOP_OAUTH_CLIENT_SECRET;

  if (!secret) {
    throw new Error(
      "Missing Convex environment variable: WHOP_OAUTH_CLIENT_SECRET"
    );
  }

  return secret;
}

/** Reads the company API key used for seller-side REST requests. */
function requireApiKey(): string {
  const apiKey = process.env.WHOP_API_KEY;

  if (!apiKey) {
    throw new Error("Missing Convex environment variable: WHOP_API_KEY");
  }

  return apiKey;
}

/**
 * Reads the public Whop application ID used as the OAuth client ID.
 *
 * Returns:
 *   The Whop app ID.
 *
 * Throws:
 *   Error when WHOP_APP_ID is not set on the deployment.
 */
function requireAppId(): string {
  const appId = process.env.WHOP_APP_ID;

  if (!appId) {
    throw new Error("Missing Convex environment variable: WHOP_APP_ID");
  }

  return appId;
}

/**
 * Reads the Whop product that grants Nof1 Plus.
 *
 * Returns:
 *   The configured product ID.
 *
 * Throws:
 *   Error when WHOP_PLUS_PRODUCT_ID is not set on the deployment.
 */
export function requireWhopPlusProductId(): string {
  const productId = process.env.WHOP_PLUS_PRODUCT_ID;

  if (!productId) {
    throw new Error("Missing Convex environment variable: WHOP_PLUS_PRODUCT_ID");
  }

  return productId;
}

/**
 * Exchanges an OAuth authorization code for a user access token.
 *
 * Params:
 *   code: Authorization code from the redirect.
 *   codeVerifier: The PKCE verifier generated by the client.
 *   redirectUri: The exact redirect URI registered with Whop.
 *
 * Returns:
 *   The user access token.
 *
 * Throws:
 *   Error when Whop rejects the exchange, which includes a replayed or
 *   expired code.
 *
 * Edge cases:
 *   The body is JSON, not form-encoded, and the client secret is required
 *   even though PKCE is in use.
 */
export async function exchangeWhopCode(
  code: string,
  codeVerifier: string,
  redirectUri: string
): Promise<string> {
  const response = await fetch(`${WHOP_OAUTH_BASE}/token`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      grant_type: "authorization_code",
      code,
      redirect_uri: redirectUri,
      client_id: requireAppId(),
      client_secret: requireOAuthClientSecret(),
      code_verifier: codeVerifier,
    }),
  });

  if (!response.ok) {
    throw new Error(
      `Whop token exchange failed with ${response.status}`
    );
  }

  const tokens = (await response.json()) as WhopTokenResponse;

  if (!tokens.access_token) {
    throw new Error("Whop token exchange returned no access token");
  }

  return tokens.access_token;
}

/**
 * Reads the Whop user behind an OAuth access token.
 *
 * Params:
 *   accessToken: User access token from the code exchange.
 *
 * Returns:
 *   The Whop user ID (`user_...`).
 *
 * Throws:
 *   Error when the userinfo call fails or returns no subject.
 *
 * Edge cases:
 *   The subject is the only identity signal used. Email is deliberately
 *   ignored: an unverified email must never link two accounts.
 */
export async function fetchWhopUserId(accessToken: string): Promise<string> {
  const response = await fetch(`${WHOP_OAUTH_BASE}/userinfo`, {
    headers: {
      Authorization: `Bearer ${accessToken}`,
      Accept: "application/json",
    },
  });

  if (!response.ok) {
    throw new Error(`Whop userinfo failed with ${response.status}`);
  }

  const info = (await response.json()) as WhopUserInfo;

  if (!info.sub) {
    throw new Error("Whop userinfo returned no subject");
  }

  return info.sub;
}

/**
 * Lists a user's memberships for the Nof1 Plus product.
 *
 * Params:
 *   whopUserId: Whop user ID to look up.
 *
 * Returns:
 *   Memberships for that user and product, possibly empty.
 *
 * Throws:
 *   Error when the request fails, so the caller retries rather than writing a
 *   grant derived from an incomplete read.
 *
 * Edge cases:
 *   Uses the seller's company credential, not the user's OAuth token, so the result
 *   reflects seller-side truth rather than what the user can see.
 */
export async function fetchWhopMemberships(
  whopUserId: string
): Promise<WhopMembership[]> {
  const productId = requireWhopPlusProductId();
  const url = new URL(`${WHOP_API_BASE}/memberships`);
  url.searchParams.set("user_id", whopUserId);
  url.searchParams.set("product_id", productId);

  const response = await fetch(url.toString(), {
    headers: {
      Authorization: `Bearer ${requireApiKey()}`,
      Accept: "application/json",
    },
  });

  if (!response.ok) {
    throw new Error(`Whop membership lookup failed with ${response.status}`);
  }

  const payload = (await response.json()) as { data?: WhopMembership[] };
  return payload.data ?? [];
}
